version: "3.7"
services:

  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    image: yuanbing/deduction-server-envoy
    ports:
      - "8080:8080"
    links:
      - deduction-server

  deduction-server:
    build:
      context: ./deduction
      dockerfile: Dockerfile
    image: yuanbing/deduction-server
    ports:
      - "9090:9090"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: yuanbing/deduction-frontend
    ports:
      - "8081:8081"
